"""Customer-record persistence contract used by support workflows.

The query side intentionally provides a cross-domain support read model. Write
operations remain named by the aggregate they modify so they can be migrated
behind their owning domain without changing the Customer Support interface.
"""

from backend.modules.domains.support_cases.customer_records_repository import (
    acquire_student_identifier_advisory_lock,
    bump_parent_version,
    bump_student_version,
    count_parent_hidden_links,
    find_active_group_for_subject,
    get_parent_row,
    get_payment_row,
    get_school_row,
    get_staff_scope_row,
    get_student_row,
    insert_audit_event,
    insert_parent_student_link,
    insert_payment,
    insert_student,
    list_active_enrollment_blockers,
    list_audit_rows,
    list_parent_student_rows,
    list_payment_rows,
    list_school_rows,
    list_student_codes,
    list_student_enrollment_rows,
    list_student_parent_invite_rows,
    list_student_parent_rows,
    next_legacy_student_id,
    remove_parent_student_link,
    search_record_rows,
    set_student_lifecycle,
    settle_payment,
    update_parent_record,
    update_payment_record,
    update_student_account_phone,
    update_student_record,
    void_payment,
)

__all__ = [
    "acquire_student_identifier_advisory_lock",
    "bump_parent_version",
    "bump_student_version",
    "count_parent_hidden_links",
    "find_active_group_for_subject",
    "get_parent_row",
    "get_payment_row",
    "get_school_row",
    "get_staff_scope_row",
    "get_student_row",
    "insert_audit_event",
    "insert_parent_student_link",
    "insert_payment",
    "insert_student",
    "list_active_enrollment_blockers",
    "list_audit_rows",
    "list_parent_student_rows",
    "list_payment_rows",
    "list_school_rows",
    "list_student_codes",
    "list_student_enrollment_rows",
    "list_student_parent_invite_rows",
    "list_student_parent_rows",
    "next_legacy_student_id",
    "remove_parent_student_link",
    "search_record_rows",
    "set_student_lifecycle",
    "settle_payment",
    "update_parent_record",
    "update_payment_record",
    "update_student_account_phone",
    "update_student_record",
    "void_payment",
]
