"""Shared Teacher Academy API v1 adapters."""

from backend.api.v1.teacher_academy.responses import (
    academy_error,
    academy_payload,
    add_assessment_response,
    assessment_scores_from_form,
    assessment_sections_from_form,
    create_academy_teacher_response,
    delete_academy_teacher_response,
    delete_assessment_response,
    form_list,
    promote_response,
    safe_credentials,
    sync_lessons_response,
    update_assignment_response,
    update_status_response,
)
from backend.api.v1.teacher_academy.schemas import (
    ACADEMY_CRITERIA_REMARKS,
    ACADEMY_SECTIONS,
    AcademyCredentials,
    AddAcademyAssessmentForm,
    CreateAcademyTeacherForm,
    PromoteAcademyTeacherForm,
    SyncAcademyLessonsForm,
    TeacherAcademyMutationResult,
    UpdateAcademyAssignmentForm,
    UpdateAcademyStatusForm,
)

__all__ = [
    "ACADEMY_CRITERIA_REMARKS",
    "ACADEMY_SECTIONS",
    "AcademyCredentials",
    "AddAcademyAssessmentForm",
    "CreateAcademyTeacherForm",
    "PromoteAcademyTeacherForm",
    "SyncAcademyLessonsForm",
    "TeacherAcademyMutationResult",
    "UpdateAcademyAssignmentForm",
    "UpdateAcademyStatusForm",
    "academy_error",
    "academy_payload",
    "add_assessment_response",
    "assessment_scores_from_form",
    "assessment_sections_from_form",
    "create_academy_teacher_response",
    "delete_academy_teacher_response",
    "delete_assessment_response",
    "form_list",
    "promote_response",
    "safe_credentials",
    "sync_lessons_response",
    "update_assignment_response",
    "update_status_response",
]
