export const routes = {
  home: "/",
  login: "/login",
  logout: "/logout",
  search: "/search",
  changePassword: "/profile/password",
  dashboard: (studentId: number | string) => `/dashboard/${studentId}`,
  resources: (studentId: number | string) => `/dashboard/${studentId}/resources`,
  rating: (studentId: number | string) => `/dashboard/${studentId}/rating-board`,
  aap: (studentId: number | string) => `/dashboard/${studentId}/aap-lessons`,
  ar: (studentId: number | string) => `/dashboard/${studentId}/ar-lessons`,
  chat: (studentId: number | string) => `/dashboard/${studentId}/chat`,
  adminTeacherCreate: "/admin/teachers",
  adminTeacherUpdate: (teacherId: number | string) => `/admin/teachers/${teacherId}`,
  adminTeacherDelete: (teacherId: number | string) => `/admin/teachers/${teacherId}/delete`,
  adminTeacherEdit: (teacherId: number | string, school = "all") =>
    `/?panel=teachers&school=${encodeURIComponent(String(school || "all"))}&edit_teacher_id=${encodeURIComponent(String(teacherId))}`,
  adminTeacherCandidateCreate: "/admin/teacher-candidates",
  adminTeacherCandidateStatus: (candidateId: number | string) => `/admin/teacher-candidates/${candidateId}/status`,
  adminTeacherCandidatePromote: (candidateId: number | string) => `/admin/teacher-candidates/${candidateId}/promote`,
  adminTeacherCandidateEventEdit: (candidateId: number | string, eventId: number | string) =>
    `/admin/teacher-candidates/${candidateId}/events/${eventId}/edit`,
  adminTeacherCandidateEventDelete: (candidateId: number | string, eventId: number | string) =>
    `/admin/teacher-candidates/${candidateId}/events/${eventId}/delete`,
  adminResourceTypeAdd: "/admin/resources/types/add",
  adminResourceTypeDelete: (typeId: number | string) => `/admin/resources/types/${typeId}/delete`,
  adminResourceTypeRename: (typeId: number | string) => `/admin/resources/types/${typeId}/rename`,
  adminResourceAdd: "/admin/resources/add",
  adminResourceDelete: (resourceId: number | string) => `/admin/resources/${resourceId}/delete`,
  adminResourceEdit: (resourceId: number | string) => `/admin/resources/${resourceId}/edit`,
  adminResourcesApi: "/admin/api/resources",
  adminStudentsApi: "/admin/api/students",
  adminComplaintsApi: "/admin/api/complaints",
  adminComplaintApi: (complaintId: number | string) => `/admin/api/complaints/${complaintId}`,
  adminStudentPaymentsApi: (studentRowId: number | string) => `/admin/api/students/${studentRowId}/payments`,
  adminStudentPaymentApi: (paymentId: number | string) => `/admin/api/student-payments/${paymentId}`,
  adminAcademicSubjectCreate: "/admin/academic/subjects",
  adminAcademicGroupCreate: "/admin/academic/groups",
  adminAcademicScheduleCreate: "/admin/api/academic/schedules",
  adminAcademicGradebookApi: (groupId: number | string) => `/admin/api/academic/gradebook?group_id=${groupId}`,
  adminAcademicAttendanceApi: "/admin/api/academic/attendance",
  adminAcademicHomeworkApi: "/admin/api/academic/homework",
  adminAcademicEnrollmentStatusApi: (enrollmentId: number | string) =>
    `/admin/api/academic/enrollments/${enrollmentId}/status`,
  adminAcademicEnrollmentGroupApi: (enrollmentId: number | string) =>
    `/admin/api/academic/enrollments/${enrollmentId}/group`,
  adminAnnouncementsApi: "/admin/api/announcements",
  adminAnnouncementApi: (announcementId: number | string) => `/admin/api/announcements/${announcementId}`,
  adminParents: "/admin/parents",
  adminParentChildrenFor: (parentAdminId: number | string) => `/admin/parents/${parentAdminId}/children`,
  adminParentChildFor: (parentAdminId: number | string, studentRowId: number | string) =>
    `/admin/parents/${parentAdminId}/children/${studentRowId}`,
  adminParentChildren: "/admin/parent-children",
  adminParentChild: (studentRowId: number | string) => `/admin/parent-children/${studentRowId}`,
  adminStudentProfile: (studentRowId: number | string) => `/admin/students/${studentRowId}`,
  adminStudentDashboard: (studentRowId: number | string, school = "all") =>
    `/admin/students/${studentRowId}/dashboard?school=${encodeURIComponent(String(school || "all"))}`,
  adminStudentDashboardTarget: (studentRowId: number | string, target: string, school = "all") =>
    `/admin/students/${studentRowId}/dashboard/${encodeURIComponent(String(target || "dashboard"))}?school=${encodeURIComponent(String(school || "all"))}`,
  adminStudentSave: (studentRowId: number | string) => `/admin/students/${studentRowId}/profile`,
};
