import { apiRoutes } from "../api/routes.ts";

const adminStudentQuery = (school = "all") =>
  `school=${encodeURIComponent(String(school || "all"))}&embed=admin`;

export const routes = {
  home: "/",
  login: "/login",
  logout: "/logout",
  search: "/search",
  accountSecurity: "/account/security",
  changePassword: "/account/security",
  dashboard: (studentId: number | string) => `/dashboard/${studentId}`,
  resources: (studentId: number | string) => `/dashboard/${studentId}/resources`,
  rating: (studentId: number | string) => `/dashboard/${studentId}/rating-board`,
  aap: (studentId: number | string) => `/dashboard/${studentId}/aap-lessons`,
  ar: (studentId: number | string) => `/dashboard/${studentId}/ar-lessons`,
  chat: (studentId: number | string) => `/dashboard/${studentId}/chat`,
  adminTeacherCreate: "/admin/teachers",
  adminTeacherUpdate: (teacherId: number | string) => `/admin/teachers/${teacherId}`,
  adminTeacherDelete: (teacherId: number | string) => `/admin/teachers/${teacherId}/delete`,
  adminTeacherEdit: (teacherId: number | string, school = "all", mode = "") =>
    `/?panel=teachers&school=${encodeURIComponent(String(school || "all"))}${
      mode ? `&mode=${encodeURIComponent(String(mode))}` : ""
    }&edit_teacher_id=${encodeURIComponent(String(teacherId))}`,
  adminTeacherCandidateCreate: "/admin/teacher-candidates",
  adminTeacherCandidateStatus: (candidateId: number | string) => `/admin/teacher-candidates/${candidateId}/status`,
  adminTeacherCandidatePromote: (candidateId: number | string) => `/admin/teacher-candidates/${candidateId}/promote`,
  adminTeacherCandidateEventEdit: (candidateId: number | string, eventId: number | string) =>
    `/admin/teacher-candidates/${candidateId}/events/${eventId}/edit`,
  adminTeacherCandidateEventDelete: (candidateId: number | string, eventId: number | string) =>
    `/admin/teacher-candidates/${candidateId}/events/${eventId}/delete`,
  academicDirectorOverview: "/academic-director",
  academicDirectorTeacherAcademy: "/academic-director/teacher-academy",
  academicDirectorHeadOfDepartments: "/academic-director/head-of-departments",
  academicDirectorGroups: "/academic-director/groups",
  academicDirectorSubjects: "/academic-director/subjects",
  academicDirectorTimetable: "/academic-director/timetable",
  academicDirectorAnnouncements: "/academic-director/announcements",
  academicDirectorProfile: "/academic-director/profile",
  academicDirectorHeadOfDepartmentCreate: apiRoutes.academicDirectorHeadOfDepartmentCreate,
  academicDirectorTeacherAcademyCreate: apiRoutes.academicDirectorTeacherAcademyCreate,
  academicDirectorTeacherAcademyAssignmentUpdate: apiRoutes.academicDirectorTeacherAcademyAssignmentUpdate,
  academicDirectorTeacherAcademyAssessmentCreate: apiRoutes.academicDirectorTeacherAcademyAssessmentCreate,
  academicDirectorTeacherAcademyAssessmentDelete: apiRoutes.academicDirectorTeacherAcademyAssessmentDelete,
  academicDirectorTeacherAcademyStatusUpdate: apiRoutes.academicDirectorTeacherAcademyStatusUpdate,
  academicDirectorTeacherAcademyLessonsSync: apiRoutes.academicDirectorTeacherAcademyLessonsSync,
  academicDirectorTeacherAcademyPromote: apiRoutes.academicDirectorTeacherAcademyPromote,
  academicDirectorTeacherAcademyDelete: apiRoutes.academicDirectorTeacherAcademyDelete,
  headOfDepartmentOverview: "/head-of-department",
  headOfDepartmentTeacherAcademy: "/head-of-department/teacher-academy",
  headOfDepartmentTimetable: "/head-of-department/timetable",
  headOfDepartmentAnnouncements: "/head-of-department/announcements",
  headOfDepartmentProfile: "/head-of-department/profile",
  headOfDepartmentTeacherAcademyAssignmentUpdate: apiRoutes.headOfDepartmentTeacherAcademyAssignmentUpdate,
  headOfDepartmentTeacherAcademyAssessmentCreate: apiRoutes.headOfDepartmentTeacherAcademyAssessmentCreate,
  headOfDepartmentTeacherAcademyAssessmentDelete: apiRoutes.headOfDepartmentTeacherAcademyAssessmentDelete,
  headOfDepartmentTeacherAcademyStatusUpdate: apiRoutes.headOfDepartmentTeacherAcademyStatusUpdate,
  headOfDepartmentTeacherAcademyLessonsSync: apiRoutes.headOfDepartmentTeacherAcademyLessonsSync,
  adminResourceTypeAdd: "/admin/resources/types/add",
  adminResourceTypeDelete: (typeId: number | string) => `/admin/resources/types/${typeId}/delete`,
  adminResourceTypeRename: (typeId: number | string) => `/admin/resources/types/${typeId}/rename`,
  adminResourceAdd: "/admin/resources/add",
  adminResourceDelete: (resourceId: number | string) => `/admin/resources/${resourceId}/delete`,
  adminResourceEdit: (resourceId: number | string) => `/admin/resources/${resourceId}/edit`,
  adminResourcesApi: "/api/v1/admin/resources",
  adminStudentsApi: "/api/v1/admin/students",
  adminComplaintsApi: "/api/v1/admin/complaints",
  adminComplaintApi: (complaintId: number | string) => `/api/v1/admin/complaints/${complaintId}`,
  adminComplaintReplies: (complaintId: number | string) =>
    `/api/v1/admin/complaints/${complaintId}/replies`,
  adminStudentPaymentsApi: (studentRowId: number | string) => `/api/v1/admin/students/${studentRowId}/payments`,
  adminStudentPaymentApi: (paymentId: number | string) => `/api/v1/admin/student-payments/${paymentId}`,
  adminAcademicSubjectCreate: "/admin/academic/subjects",
  adminAcademicSchoolCreate: "/admin/academic/schools",
  adminAcademicGroupCreate: "/admin/academic/groups",
  adminAcademicContextApi: "/api/v1/admin/academic/context",
  adminAcademicGroupApi: (groupId: number | string) => `/api/v1/admin/academic/groups/${groupId}`,
  adminAcademicScheduleCreate: "/api/v1/admin/academic/schedules",
  adminAcademicGradebookApi: (groupId: number | string) => `/api/v1/admin/academic/gradebook?group_id=${groupId}`,
  adminAcademicAttendanceApi: "/api/v1/admin/academic/attendance",
  adminAcademicHomeworkApi: "/api/v1/admin/academic/homework",
  adminAcademicExamApi: "/api/v1/admin/academic/exams",
  adminAcademicLessonApi: (lessonSessionId: number | string) => `/api/v1/admin/academic/lessons/${lessonSessionId}`,
  adminAcademicEnrollmentStatusApi: (enrollmentId: number | string) =>
    `/api/v1/admin/academic/enrollments/${enrollmentId}/status`,
  adminAcademicEnrollmentGroupApi: (enrollmentId: number | string) =>
    `/api/v1/admin/academic/enrollments/${enrollmentId}/group`,
  academicDirectorAcademicSchoolCreate: apiRoutes.academicDirectorAcademicSchoolCreate,
  academicDirectorAcademicGroupCreate: apiRoutes.academicDirectorAcademicGroupCreate,
  academicDirectorAcademicContextApi: apiRoutes.academicDirectorAcademicContextApi,
  academicDirectorAcademicGroupApi: apiRoutes.academicDirectorAcademicGroupApi,
  academicDirectorAcademicScheduleCreate: apiRoutes.academicDirectorAcademicScheduleCreate,
  academicDirectorAcademicGradebookApi: apiRoutes.academicDirectorAcademicGradebookApi,
  academicDirectorAcademicAttendanceApi: apiRoutes.academicDirectorAcademicAttendanceApi,
  academicDirectorAcademicHomeworkApi: apiRoutes.academicDirectorAcademicHomeworkApi,
  academicDirectorAcademicExamApi: apiRoutes.academicDirectorAcademicExamApi,
  academicDirectorAcademicLessonApi: apiRoutes.academicDirectorAcademicLessonApi,
  academicDirectorAcademicEnrollmentStatusApi: apiRoutes.academicDirectorAcademicEnrollmentStatusApi,
  academicDirectorAcademicEnrollmentGroupApi: apiRoutes.academicDirectorAcademicEnrollmentGroupApi,
  adminAnnouncementsApi: "/api/v1/admin/announcements",
  adminAnnouncementApi: (announcementId: number | string) => `/api/v1/admin/announcements/${announcementId}`,
  adminParentInvite: (studentRowId: number | string) =>
    `/api/v1/admin/students/${studentRowId}/parent-invite`,
  adminParentAccount: (parentAdminId: number | string) => `/api/v1/admin/parents/${parentAdminId}`,
  adminParentChildrenFor: (parentAdminId: number | string) => `/api/v1/admin/parents/${parentAdminId}/children`,
  adminParentChildFor: (parentAdminId: number | string, studentRowId: number | string) =>
    `/api/v1/admin/parents/${parentAdminId}/children/${studentRowId}`,
  adminParentChildren: "/api/v1/admin/parent-children",
  adminParentChild: (studentRowId: number | string) => `/api/v1/admin/parent-children/${studentRowId}`,
  parentStudentDashboard: (studentRowId: number | string) => `/parent/dashboard/${studentRowId}`,
  adminStudentProfile: (studentRowId: number | string) => `/admin/students/${studentRowId}`,
  adminStudentPanel: (studentRowId: number | string, school = "all", panel = "student_dashboard") =>
    `/?panel=${encodeURIComponent(String(panel || "student_dashboard"))}&school=${encodeURIComponent(String(school || "all"))}&student=${encodeURIComponent(String(studentRowId))}`,
  adminStudentDashboard: (studentRowId: number | string, school = "all") =>
    `/admin/students/${studentRowId}/dashboard?${adminStudentQuery(school)}`,
  adminStudentDashboardTarget: (studentRowId: number | string, target: string, school = "all") =>
    `/admin/students/${studentRowId}/dashboard/${encodeURIComponent(String(target || "dashboard"))}?${adminStudentQuery(school)}`,
  adminStudentSave: (studentRowId: number | string) => `/admin/students/${studentRowId}/profile`,
};
