"""Re-export role constants, permission constants, and FastAPI security dependencies."""

from backend.core.access.roles import (
    ROLE_CEO,
    ROLE_CUSTOMER_SUPPORT,
    ROLE_PARENT,
    ROLE_STUDENT,
    ROLE_HEAD_OF_DEPARTMENT,
    ROLE_HR_MANAGER,
    ALL_ROLES,
    normalize_role,
)
from backend.core.access.management_permissions import (
    PERMISSION_VIEW_DASHBOARD,
    PERMISSION_MANAGE_STUDENTS,
    PERMISSION_MANAGE_TEACHERS,
    PERMISSION_MANAGE_PARENTS,
    PERMISSION_MANAGE_ANNOUNCEMENTS,
    PERMISSION_MANAGE_RESOURCES,
    PERMISSION_MANAGE_COMPLAINTS,
    PERMISSION_MANAGE_PAYMENTS,
    PERMISSION_MANAGE_ACADEMICS,
    PERMISSION_MANAGE_RECRUITMENT,
    ALL_PERMISSIONS,
    role_has_permission,
)
from backend.core.access.api import (
    CurrentUser,
    get_actor_context,
    get_current_user,
    get_current_user_role,
    require_role,
    require_permission,
)
from backend.core.access.capabilities import (
    access_defaults_for_role,
    capabilities_for_role,
    role_has_capability,
)
from backend.core.access.context import (
    ActorContext,
    SchoolScope,
    actor_context_from_session,
    resolve_actor_context,
)
from backend.core.access.domain_types import (
    Capability,
    Domain,
    ObjectScope,
    PersonType,
    Role,
    SchoolScopeMode,
)

__all__ = [
    "ROLE_CEO",
    "ROLE_CUSTOMER_SUPPORT",
    "ROLE_PARENT",
    "ROLE_STUDENT",
    "ROLE_HEAD_OF_DEPARTMENT",
    "ROLE_HR_MANAGER",
    "ALL_ROLES",
    "normalize_role",
    "PERMISSION_VIEW_DASHBOARD",
    "PERMISSION_MANAGE_STUDENTS",
    "PERMISSION_MANAGE_TEACHERS",
    "PERMISSION_MANAGE_PARENTS",
    "PERMISSION_MANAGE_ANNOUNCEMENTS",
    "PERMISSION_MANAGE_RESOURCES",
    "PERMISSION_MANAGE_COMPLAINTS",
    "PERMISSION_MANAGE_PAYMENTS",
    "PERMISSION_MANAGE_ACADEMICS",
    "PERMISSION_MANAGE_RECRUITMENT",
    "ALL_PERMISSIONS",
    "role_has_permission",
    "CurrentUser",
    "ActorContext",
    "SchoolScope",
    "Capability",
    "Domain",
    "ObjectScope",
    "PersonType",
    "Role",
    "SchoolScopeMode",
    "access_defaults_for_role",
    "actor_context_from_session",
    "resolve_actor_context",
    "capabilities_for_role",
    "role_has_capability",
    "get_actor_context",
    "get_current_user",
    "get_current_user_role",
    "require_role",
    "require_permission",
]
