"""Coarse permissions used by authenticated JSON management APIs."""

from backend.core.access import roles


PERMISSION_VIEW_DASHBOARD = "view_dashboard"
PERMISSION_MANAGE_STUDENTS = "manage_students"
PERMISSION_MANAGE_TEACHERS = "manage_teachers"
PERMISSION_MANAGE_PARENTS = "manage_parents"
PERMISSION_MANAGE_ANNOUNCEMENTS = "manage_announcements"
PERMISSION_MANAGE_RESOURCES = "manage_resources"
PERMISSION_MANAGE_COMPLAINTS = "manage_complaints"
PERMISSION_MANAGE_PAYMENTS = "manage_payments"
PERMISSION_MANAGE_ACADEMICS = "manage_academics"
PERMISSION_SYSTEM_SETTINGS = "system_settings"

ALL_PERMISSIONS = {
    PERMISSION_VIEW_DASHBOARD,
    PERMISSION_MANAGE_STUDENTS,
    PERMISSION_MANAGE_TEACHERS,
    PERMISSION_MANAGE_PARENTS,
    PERMISSION_MANAGE_ANNOUNCEMENTS,
    PERMISSION_MANAGE_RESOURCES,
    PERMISSION_MANAGE_COMPLAINTS,
    PERMISSION_MANAGE_PAYMENTS,
    PERMISSION_MANAGE_ACADEMICS,
    PERMISSION_SYSTEM_SETTINGS,
}

ROLE_PERMISSIONS = {
    roles.ROLE_OWNER: ALL_PERMISSIONS,
    roles.ROLE_SYSTEM_ADMIN: ALL_PERMISSIONS,
    roles.ROLE_CEO: {
        PERMISSION_VIEW_DASHBOARD,
        PERMISSION_MANAGE_STUDENTS,
        PERMISSION_MANAGE_PARENTS,
        PERMISSION_MANAGE_ANNOUNCEMENTS,
        PERMISSION_MANAGE_RESOURCES,
        PERMISSION_MANAGE_COMPLAINTS,
        PERMISSION_MANAGE_PAYMENTS,
    },
    roles.ROLE_ADMIN: {
        PERMISSION_VIEW_DASHBOARD,
        PERMISSION_MANAGE_STUDENTS,
        PERMISSION_MANAGE_TEACHERS,
        PERMISSION_MANAGE_PARENTS,
        PERMISSION_MANAGE_ANNOUNCEMENTS,
        PERMISSION_MANAGE_RESOURCES,
        PERMISSION_MANAGE_COMPLAINTS,
        PERMISSION_MANAGE_PAYMENTS,
        PERMISSION_MANAGE_ACADEMICS,
    },
    roles.ROLE_HR_MANAGER: {
        PERMISSION_VIEW_DASHBOARD,
        PERMISSION_MANAGE_TEACHERS,
    },
    roles.ROLE_ACADEMIC_DIRECTOR: {
        PERMISSION_VIEW_DASHBOARD,
        PERMISSION_MANAGE_TEACHERS,
        PERMISSION_MANAGE_RESOURCES,
        PERMISSION_MANAGE_ACADEMICS,
        PERMISSION_MANAGE_STUDENTS,
    },
    roles.ROLE_HEAD_OF_DEPARTMENT: {
        PERMISSION_VIEW_DASHBOARD,
        PERMISSION_MANAGE_TEACHERS,
        PERMISSION_MANAGE_ACADEMICS,
    },
    roles.ROLE_CUSTOMER_SUPPORT: {
        PERMISSION_VIEW_DASHBOARD,
        PERMISSION_MANAGE_COMPLAINTS,
    },
    roles.ROLE_PARENT: {PERMISSION_VIEW_DASHBOARD},
    roles.ROLE_STUDENT: {PERMISSION_VIEW_DASHBOARD},
}


def role_has_permission(role: str, permission: str) -> bool:
    normalized_role = roles.normalize_role(role)
    return permission in ROLE_PERMISSIONS.get(normalized_role, set())
